import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import { existsSync } from 'fs';

/**
 * Generate markdown file for pending approval
 * Creates a file in /Pending_Approval directory before executing Odoo operations
 */
export class MarkdownOutputGenerator {
  constructor(outputDir) {
    this.outputDir = outputDir;
  }

  /**
   * Ensure output directory exists
   */
  async ensureDirectory() {
    if (!existsSync(this.outputDir)) {
      await mkdir(this.outputDir, { recursive: true });
    }
  }

  /**
   * Generate timestamp for filename
   */
  generateTimestamp() {
    const now = new Date();
    return now.toISOString().replace(/[:.]/g, '-').slice(0, -5);
  }

  /**
   * Generate markdown for draft invoice creation
   */
  async generateInvoiceDraft(invoiceData, preview = true) {
    await this.ensureDirectory();

    const timestamp = this.generateTimestamp();
    const filename = `INVOICE_DRAFT_${timestamp}.md`;
    const filepath = join(this.outputDir, filename);

    const lines = invoiceData.invoiceLineIds?.map((line, index) => {
      const lineTotal = (line.quantity || 1) * (line.priceUnit || line.price_unit || 0);
      return `| ${index + 1} | ${line.name || line.description || 'N/A'} | ${line.quantity || 1} | ${(line.priceUnit || line.price_unit || 0).toFixed(2)} | ${lineTotal.toFixed(2)} |`;
    }).join('\n') || '| - | No items | - | - | 0.00 |';

    const totalAmount = invoiceData.invoiceLineIds?.reduce((sum, line) => {
      return sum + ((line.quantity || 1) * (line.priceUnit || line.price_unit || 0));
    }, 0) || 0;

    const content = `# 📄 Draft Invoice - Pending Approval

**Generated:** ${new Date().toISOString()}
**Status:** ⏳ Awaiting Approval

---

## Invoice Details

| Field | Value |
|-------|-------|
| Partner ID | ${invoiceData.partnerId || 'N/A'} |
| Invoice Date | ${invoiceData.invoiceDate || 'Today'} |
| Due Date | ${invoiceData.dueDate || 'As per payment terms'} |
| Payment Terms | ${invoiceData.paymentTermId ? `ID: ${invoiceData.paymentTermId}` : 'Default'} |
| Fiscal Position | ${invoiceData.fiscalPositionId ? `ID: ${invoiceData.fiscalPositionId}` : 'None'} |
| Company ID | ${invoiceData.companyId || 'Default'} |

---

## Invoice Lines

| # | Description | Quantity | Unit Price | Total |
|---|-------------|----------|------------|-------|
${lines}

---

## Totals

| | Amount |
|---|--------|
| **Subtotal** | ${totalAmount.toFixed(2)} |
| **Tax** | Calculated by Odoo |
| **Total** | **${totalAmount.toFixed(2)}** |

---

## Narrative

${invoiceData.narrative || '*No narrative provided*'}

---

## Approval Required

⚠️ **This invoice will be created in DRAFT state** and will require manual review in Odoo before posting.

### Actions

- [ ] Review invoice details
- [ ] Verify partner information
- [ ] Confirm line items and pricing
- [ ] Approve for creation in Odoo

---

## Execution Details

- **Operation:** Create Draft Invoice
- **Target System:** Odoo ERP (JSON-RPC)
- **Model:** account.move
- **State:** draft

---

*This file was auto-generated by Odoo MCP Server*
`;

    await writeFile(filepath, content, 'utf-8');

    return {
      filepath,
      filename,
      preview: !preview,
      message: preview 
        ? `Preview generated. File saved to: ${filepath}`
        : `Invoice draft documented. File saved to: ${filepath}`
    };
  }

  /**
   * Generate markdown for payment registration
   */
  async generatePaymentDraft(paymentData, preview = true) {
    await this.ensureDirectory();

    const timestamp = this.generateTimestamp();
    const filename = `PAYMENT_REG_${timestamp}.md`;
    const filepath = join(this.outputDir, filename);

    const content = `# 💰 Payment Registration - Pending Approval

**Generated:** ${new Date().toISOString()}
**Status:** ⏳ Awaiting Approval

---

## Payment Details

| Field | Value |
|-------|-------|
| Invoice ID | ${paymentData.invoiceId || 'N/A'} |
| Payment Amount | **${(paymentData.amount || 0).toFixed(2)}** |
| Payment Date | ${paymentData.paymentDate || 'Today'} |
| Payment Reference | ${paymentData.paymentReference || 'N/A'} |
| Communication | ${paymentData.communication || 'N/A'} |
| Journal ID | ${paymentData.journalId || 'Auto-selected'} |
| Payment Method | ${paymentData.paymentMethodId ? `ID: ${paymentData.paymentMethodId}` : 'Default'} |
| Company ID | ${paymentData.companyId || 'Default'} |

---

## Invoice Information

| Field | Value |
|-------|-------|
| Invoice ID | ${paymentData.invoiceId} |
| Expected Action | Reconcile payment with invoice |

---

## Approval Required

⚠️ **This payment will be registered and confirmed** in Odoo, affecting:
- Bank/Cash journal balance
- Invoice payment status
- Partner ledger

### Actions

- [ ] Verify invoice exists and is posted
- [ ] Confirm payment amount matches invoice
- [ ] Validate payment date
- [ ] Approve payment registration

---

## Execution Details

- **Operation:** Register Payment
- **Target System:** Odoo ERP (JSON-RPC)
- **Model:** account.payment
- **Actions:** Create → Post → Reconcile

---

*This file was auto-generated by Odoo MCP Server*
`;

    await writeFile(filepath, content, 'utf-8');

    return {
      filepath,
      filename,
      preview: !preview,
      message: preview
        ? `Preview generated. File saved to: ${filepath}`
        : `Payment registration documented. File saved to: ${filepath}`
    };
  }

  /**
   * Generate a summary/approval log
   */
  async generateApprovalLog(operations) {
    await this.ensureDirectory();

    const timestamp = this.generateTimestamp();
    const filename = `APPROVAL_LOG_${timestamp}.md`;
    const filepath = join(this.outputDir, filename);

    const operationRows = operations.map((op, index) => {
      const status = op.executed ? '✅ Executed' : '⏳ Pending';
      return `| ${index + 1} | ${op.type} | ${op.description} | ${status} | ${op.timestamp} |`;
    }).join('\n');

    const content = `# 📋 Approval Log

**Generated:** ${new Date().toISOString()}

---

## Operations Summary

| # | Type | Description | Status | Timestamp |
|---|------|-------------|--------|-----------|
${operationRows}

---

## Notes

This log tracks all operations that went through the approval process.

---

*This file was auto-generated by Odoo MCP Server*
`;

    await writeFile(filepath, content, 'utf-8');

    return { filepath, filename };
  }
}

export default MarkdownOutputGenerator;
