#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Weekly Briefing Generator - Silver Tier Feature

Generates a weekly CEO briefing summarizing all AI Employee activities.

Usage:
    python briefing_generator.py --weekly
"""

import argparse
import json
import os
from datetime import datetime, timedelta
from pathlib import Path

VAULT_PATH = Path(os.environ.get('AI_VAULT_PATH', r'D:\Personal Ai Employee\AI_Employee_Vault'))
BRIEFINGS_PATH = VAULT_PATH / 'Briefings'
LOGS_PATH = VAULT_PATH / 'Logs'
BRIEFING_LOG = LOGS_PATH / 'approvals.jsonl'

BRIEFINGS_PATH.mkdir(parents=True, exist_ok=True)


def load_approval_log(days: int = 7) -> list:
    """Load approval log entries for the last N days."""
    entries = []
    cutoff = (datetime.now() - timedelta(days=days)).strftime('%Y-%m-%d')
    
    if not BRIEFING_LOG.exists():
        return entries
    
    with open(BRIEFING_LOG, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                entry = json.loads(line.strip())
                timestamp = entry.get('timestamp', '')[:10]
                if timestamp >= cutoff:
                    entries.append(entry)
            except:
                continue
    return entries


def generate_weekly_briefing() -> str:
    """Generate a weekly briefing document."""
    now = datetime.now()
    start_date = (now - timedelta(days=7)).date()
    
    approvals = load_approval_log(7)
    approved_count = sum(1 for a in approvals if a.get('action') == 'approve')
    rejected_count = sum(1 for a in approvals if a.get('action') == 'reject')
    
    content = f"""---
type: weekly_briefing
period_start: {start_date}
generated_at: {now.isoformat()}
---

# Weekly CEO Briefing

## Week of {start_date} to {now.date()}

### Key Metrics

| Metric | Value |
|--------|-------|
| Total Approvals | {len(approvals)} |
| Approved | {approved_count} |
| Rejected | {rejected_count} |

---

## Approved Actions

"""
    
    if approvals:
        for entry in sorted(approvals, key=lambda x: x.get('timestamp', ''), reverse=True)[:10]:
            date = entry.get('timestamp', '')[:10]
            action = entry.get('action', 'unknown').upper()
            file_name = entry.get('file', 'unknown')
            content += f"- [{date}] {action}: {file_name}\n"
    else:
        content += "*No approval actions this week.*\n"
    
    content += f"""
---

*Generated by AI Employee v0.2 (Silver Tier)*
"""
    
    return content


def main():
    parser = argparse.ArgumentParser(description='Briefing Generator')
    parser.add_argument('--weekly', action='store_true', help='Generate weekly briefing')
    args = parser.parse_args()
    
    if args.weekly:
        content = generate_weekly_briefing()
        filename = f"WEEKLY_BRIEFING_{datetime.now().strftime('%Y-W%W')}.md"
        filepath = BRIEFINGS_PATH / filename
        filepath.write_text(content, encoding='utf-8')
        print(f"✅ Briefing saved: {filepath}")
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
