#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Dashboard Updater - Silver Tier Feature

Updates the main Dashboard.md with current statistics and status.
Run periodically to keep the dashboard fresh.

Usage:
    python dashboard_updater.py
"""

import json
import os
import re
from datetime import datetime, timedelta
from pathlib import Path


# Configuration
VAULT_PATH = Path(os.environ.get('AI_VAULT_PATH', r'D:\Personal Ai Employee\AI_Employee_Vault'))
DASHBOARD_PATH = VAULT_PATH / 'Dashboard.md'
LOG_FILE = VAULT_PATH / 'Logs' / 'dashboard_updater.log'


def log_message(message: str, level: str = "INFO"):
    """Log a message to the log file."""
    timestamp = datetime.now().isoformat()
    log_entry = f"[{timestamp}] [{level}] {message}\n"
    with open(LOG_FILE, 'a', encoding='utf-8') as f:
        f.write(log_entry)


def count_files(folder: Path, pattern: str = '*.md') -> int:
    """Count files in a folder."""
    if not folder.exists():
        return 0
    return len(list(folder.glob(pattern)))


def get_recent_files(folder: Path, hours: int = 24) -> int:
    """Count files modified in the last N hours."""
    if not folder.exists():
        return 0
    
    cutoff = datetime.now() - timedelta(hours=hours)
    count = 0
    for f in folder.glob('*.md'):
        try:
            mtime = datetime.fromtimestamp(f.stat().st_mtime)
            if mtime > cutoff:
                count += 1
        except:
            continue
    return count


def get_approval_status() -> dict:
    """Get pending approval count and details."""
    pending_path = VAULT_PATH / 'Pending_Approval'
    pending_items = list(pending_path.glob('*.md')) if pending_path.exists() else []
    
    return {
        'count': len(pending_items),
        'items': [f.name for f in pending_items[:5]]
    }


def generate_dashboard() -> str:
    """Generate updated dashboard content."""
    now = datetime.now()
    
    inbox_count = count_files(VAULT_PATH / 'Inbox')
    needs_action_count = count_files(VAULT_PATH / 'Needs_Action')
    pending_count = count_files(VAULT_PATH / 'Pending_Approval')
    plans_count = count_files(VAULT_PATH / 'Plans')
    done_today = get_recent_files(VAULT_PATH / 'Done', hours=24)
    done_week = get_recent_files(VAULT_PATH / 'Done', hours=168)
    
    approval_status = get_approval_status()
    
    inbox_status = "✅ Clear" if inbox_count == 0 else f"⚠️ {inbox_count} items"
    pending_status = "✅ Clear" if pending_count == 0 else f"⚠️ {pending_count} pending"
    
    return f"""---
last_updated: {now.strftime('%Y-%m-%dT%H:%M:%S')}
status: active
---

# 📊 AI Employee Dashboard

## Quick Stats

| Metric | Value | Status |
|--------|-------|--------|
| Pending Tasks | {needs_action_count} | {"✅ Clear" if needs_action_count == 0 else f"⚠️ {needs_action_count}"} |
| Awaiting Approval | {approval_status['count']} | {pending_status} |
| Tasks Completed Today | {done_today} | {"-" if done_today == 0 else "✅ Active"} |
| Tasks Completed This Week | {done_week} | - |

## 📅 Inbox Status

- **Inbox**: {inbox_count} items
- **Needs Action**: {needs_action_count} items
- **Pending Approval**: {pending_count} items
- **Active Plans**: {plans_count} items

## 💰 Financial Summary

| Period | Revenue | Expenses | Net |
|--------|---------|----------|-----|
| This Week | $0 | $0 | $0 |
| This Month | $0 | $0 | $0 |
| This Quarter | $0 | $0 | $0 |

## 🚨 Alerts

{f"- ⚠️ **{pending_count} items pending approval**" if pending_count > 0 else "- ✅ All systems operational"}

---

*Generated by AI Employee v0.2 (Silver Tier)*
"""


def update_dashboard():
    """Update the dashboard file."""
    log_message("Updating dashboard...")
    content = generate_dashboard()
    
    with open(DASHBOARD_PATH, 'w', encoding='utf-8') as f:
        f.write(content)
    
    log_message(f"Dashboard updated: {DASHBOARD_PATH}")
    print("✅ Dashboard updated successfully!")


if __name__ == '__main__':
    update_dashboard()
